language: elixir
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19
  - 20
  - 21
matrix:
  exclude:
    - otp_release: 20.0
      elixir: 1.3.4
    - otp_release: 21
      elixir: 1.3.4
notifications:
  recipients:
    - lafontaine.philippe@bleushan.com
