language: elixir
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.1
matrix:
  exclude:
    - otp_release: 20.3
      elixir: 1.3
    - otp_release: 21.1
      elixir: 1.3
    - otp_release: 21.1
      elixir: 1.4
    - otp_release: 21.1
      elixir: 1.5
notifications:
  recipients:
    - lafontaine.philippe@bleushan.com
